menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/yangsoon
    zhihu: https://www.zhihu.com/people/song-yang-91-69/activities
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
gitment:
    enable: true
    owner: yangsoon
    repo: yangsoon.github.io
    client_id: c6e81705ee274d631d1d
    client_secret: d2366443245bc5528fc5a73af235d9e23d14e33a
# Analytics
# google-analytics:
ga: UA-117274875-1

# Copyright Infomation
startyear: 2015
